spring:
  r2dbc:
    url: r2dbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: ${DB_INITIAL_POOL_SIZE}
      max-size: ${DB_MAX_POOL_SIZE}
  flyway:
    enabled: true
    table: _flyway_schema_history
    url: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

crypto:
  jwt:
    secret: ${CRYPTO_JWT_SECRET}
    access: ${CRYPTO_JWT_ACCESS_MINUTES}
    refresh: ${CRYPTO_JWT_REFRESH_MONTH}