CREATE TABLE IF NOT EXISTS USERS
(
    ID              UUID            NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    EMAIL           TEXT            NOT NULL,
    ROLE            VARCHAR(30)     NOT NULL
                    CHECK (ROLE IN ('ROLE_ADMIN', 'ROLE_USER')),
    STATUS          VARCHAR(30)     NOT NULL
                    CHECK (STATUS IN ('CREATED', 'VERIFIED', 'ACTIVE', 'DELETED')),
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE UNIQUE INDEX UNQ_USER_EMAIL ON USERS(EMAIL);