CREATE TABLE IF NOT EXISTS JOB_POSITIONS
(
    ID                  UUID           NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NAME                TEXT           NOT NULL UNIQUE,
    CREATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX UNQ_JOB_POSITION_NAME ON JOB_POSITIONS(NAME);