CREATE TABLE IF NOT EXISTS TOKENS
(
    ID                  UUID           NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID             UUID           NOT NULL REFERENCES USERS(ID),
    TOKEN               TEXT           NOT NULL,
    TYPE                VARCHAR(30)    NOT NULL
                        CHECK (TYPE IN ('ACCESS', 'REFRESH')),
    CREATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_TOKENS_USER_ID ON TOKENS(USER_ID);