CREATE TABLE IF NOT EXISTS PROFILES
(
    ID                  UUID           NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    FIRSTNAME           TEXT           NOT NULL,
    LASTNAME            TEXT           NOT NULL,
    BIRTH_DATE          DATE           NOT NULL,
    ADDRESS             TEXT           NOT NULL,
    START_DATE          DATE           NOT NULL,
    PHONE               VARCHAR(20)    NOT NULL UNIQUE,
    TELEGRAM_LINK       VARCHAR        NOT NULL UNIQUE,
    CREATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID             UUID           NOT NULL REFERENCES USERS(ID),
    JOB_POSITION_ID     UUID           NOT NULL REFERENCES JOB_POSITIONS(ID)
);

CREATE INDEX UNQ_PROFILES_PHONE ON PROFILES(PHONE);
CREATE INDEX UNQ_PROFILES_TELEGRAM_LINK ON PROFILES(TELEGRAM_LINK);
CREATE INDEX IDX_PROFILES_USER_ID ON PROFILES(USER_ID);
CREATE INDEX IDX_PROFILES_JOB_POSITION_ID ON PROFILES(JOB_POSITION_ID);