CREATE TABLE IF NOT EXISTS PASSWORDS
(
    ID                  UUID           NOT NULL PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID             UUID           NOT NULL REFERENCES USERS(ID),
    PWD                 TEXT           NOT NULL,
    STATUS              VARCHAR(30)    NOT NULL
            CHECK (STATUS IN ('ACTIVE', 'EXPIRED')),
    CREATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_PASSWORDS_USER_ID ON PASSWORDS(USER_ID);